### ISSUE TITLE
Reorder errors in error-list

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#16]
Comments can be added (starting with #) to separate sections.

**Comment by mukrop** [comment]
I see you've worked on this in 1537537. If you feel you've already done the issue, feel free to close it.
By the way, if you mention the issue in the commit message (writing #16), the relevant commit link will be added here.

**Comment by zacikpa** [comment]
I plan to take a second look at it to see if there's something worth changing.
Thanks for the advice!

**Comment by mukrop** [comment]
I've added sectioning to the website.
We can do the sectioning and reordering together when we meet: The section should be reasonably-sized and easily navigable (as they now set the structure of the whole page).

**Comment by mukrop** [comment]
Done.
