### ISSUE TITLE
Choose common libraries

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#2]
Based on Petr's paper

**Comment by mukrop** [comment]
How was the paper? I read it again as well (it is not a very easy read). Was it understandable enough for you? Any questions?
What libraries would you then suggest to use? (It may be worth making some notes out of this in gDrive for future reference -- the selection, relevant frequency ratios and other notes.)

**Comment by zacikpa** [comment]
Definitely not an easy read, I got through it but should probably do it again. I didn't really grasp the process of key classification but I guess that part is not as important for us as the results.
Is the Certificate Transparency scan more relevant to our research than the TLS scan?
If I had to make a wide list of what libraries to use, it would include:
OpenSSL
BouncyCastle
GnuTLS
libgcrypt
Microsoft CryptoAPI
mbedTLS
Botan
WolfSSL

**Comment by mukrop** [comment]
* The key classification process was not really described in the paper, they mainly referenced the previous one for that (and no, it's not worth looking it up in detail).
* CT vs TLS dataset: Well, depends. CT will have younger data ("new, fresh" certificates). Gradually, browsers (mainly Chrome) expects all TLS certificates to be in CT logs, so it should coincide eventually. I would go with the TLS scan.
* As for your list: I have a couple of questions:
    * Why not go for OpenJDK? I think it's probably more used than BouncyCastle.
    * I gather you made a substitution Nettle -> GnuTLS. It's worth to look up if there is not some else prominent library using Nettle.
    * From the reasonably used groups, you miss Crypto++, LibTomCrypt and cryptlib. Anecdotally, I do agree these are less known -- do you have any rigorous reason to throw them out of the mix?

**Comment by zacikpa** [comment]
Answering the questions:

- regarding OpenJDK / BouncyCastle:
If that's the case, than we should go for that one. The documentation of BouncyCastle links to the documentation of OpenJDK so I figured it uses OpenJDK in some way and the errors would be same for both. (Correct me if I'm wrong.)

-  regarding Nettle / GnuTLS
I haven't been able to find any other library like that yet, but I can look into it again.

- regarding Crypto++, LibTomCrypt and cryptlib
From what I've observed, neither Crypto++ nor LibTomCrypt work with certificates in any way. 
As for cryptlib, I couldn't find any documentation to it until today and it all looked to me as if it wasn't updated for a while. However, I managed to find something today so I guess we could add it to the mix.

**Comment by mukrop** [comment]
* OpenJDK / BouncyCastle:
  Java works in the system of crypto providers with shared interfaces. That means that the OpenJDK defines the unified interface (and a basic implementation) and allows to use different providers (e.g. BouncyCastle) to be used instead of the basic implementation. That means the providers have to adhere to the prescribed interface. I'm not sure if this includes also error messages (bud probably so). Anyway, there's usually also a separate way to access the provider to gain access to extra features it may have (thus circumventing the shared interface). Thus, it may or may not have separate error messages.
* Nettle / GnuTLS
  I haven't checked either, was just asking. Let's double-check and if nothing is found, keep GnuTLS.
* Crypto++, LibTomCrypt and cryptlib
  Ack, that sounds reasonable.

**Comment by mukrop** [comment]
Do a write-up of what we use and why (that could be also published on the web one day).

**Comment by zacikpa** [comment]
The write-up is in the work gDrive for now.
