### ISSUE TITLE
Set up a local build

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#20]
On your local machine, set up and test a local build. At least `make certs` and `make web` should succeed. If you decide to install Jekyll, `make web-local` should also succeed.

You should not push changes that do not compile locally -- currently, the build is broken (you're getting notification emails with every still failing push). This in practice means the web deploy will not run and I cannot see my changes online.

**Comment by mukrop** [comment]
I've fixed some things, but cc misses a CRL template file I don't have (and it seems it was not in the previous version either). For the moment, I've deleted the folder (b41bdab). When looking into it, you can use the content of the files as they were deleted (and fix them :-P).

**Comment by mukrop** [comment]
Closed accidentally, I still want you to set up a local build and attempt to build before pushing.

**Comment by zacikpa** [comment]
I'll take a look at it as soon as I can.

**Comment by zacikpa** [comment]
Tried setting up the local build, will close the issue after I install and test Jekyll sometime in near future.

**Comment by mukrop** [comment]
OK :-).

**Comment by zacikpa** [comment]
Succesfully built the web locally, closing the issue.
