### ISSUE TITLE
Check OpenSSL version on Travis

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#22]
Check which version of OpenSSL runs on Travis CI. Consider using the current master, i.e. building our own.

**Comment by mukrop** [comment]
Travis uses 1.0.2g, that is old. We want newer.

**Comment by zacikpa** [comment]
I tried installing Openssl on Travis machine manually, it took more than 5 minutes. However, there is an option to run the machine not on Ubuntu 16.04 (which uses old OpenSSL), but on Ubuntu 18.04 (which uses OpenSSL 1.1.1.) I tried to build it that way and everything worked fine. Wouldn't it be easier to solve it this way?

**Comment by mukrop** [comment]
Definitely so, go with the new Ubuntu.

**Comment by zacikpa** [comment]
Done, the build fails, but that is not related to this change. See comment on 6700cb7.
