### ISSUE TITLE
Add descriptive introductions to error categories

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#25]
* Saved in `web/_data/error.yml`.
* Displayed on the home page between the title and the error list.
* Listing the relevant names (e.g. official extension names) and linking the relevant RFCs.

**Comment by zacikpa** [comment]
> linking the relevant RFCs.

The only relevant RFC i know about for most errors is RFC 5280. (The only exception being RFC 3779 for the "unnested resource" error.)
Should we really have it at every category? Or should we add links to specific parts of it, for example linking https://tools.ietf.org/html/rfc5280#section-4.2.1.3 at Key Usage errors?

**Comment by mukrop** [comment]
Linking to specific parts would be rather useful, in my view.

**Comment by zacikpa** [comment]
Done in ebe1327.
