### ISSUE TITLE
Add missing error folders 

### ISSUE THREAD

**Issue by zacikpa** [crocs-muni/usable-cert-validation#28]
There is 3 of them:
X509_V_OK
X509_V_ERR_UNSPECIFIED
X509_V_ERR_PROXY_SUBJECT_INVALID

**Comment by zacikpa** [comment]
Already done with e71f0

**Comment by mukrop** [comment]
Pro tip (GutHub): If you write "Resolves #28", "Fixes #28" or similar in the commit message, the GitHub backend will automatically add the commit reference to the issue and close it.
Relevant documentation: https://help.github.com/en/articles/closing-issues-using-keywords
