### ISSUE TITLE
Compare errors in various libraries

### ISSUE THREAD

**Issue by zacikpa** [crocs-muni/usable-cert-validation#30]
Install libraries, run a CLI where available, otherwise write validation code.

- [x] GnuTLS
- [ ] NSS
- [ ] GnuPG
- [ ] mBedTLS
- [ ] Microsoft CryptoAPI
- [ ] Botan
- [ ] WolfSSL
- [ ] OpenJDK

**Comment by mukrop** [comment]
Long-term goal, will be broken into smaller issues.
