### ISSUE TITLE
[BUG] GH link errors on the website

### ISSUE THREAD

**Issue by webknjaz** [crocs-muni/usable-cert-validation#38]
On the website, in the error list, there's "the project GitHub" links. Clicking on them results in 404.

One example is https://github.com/crocs-muni/usable-cert-validation/tree/master/errors/X509_%C2%ADV_%C2%ADERR_%C2%ADCERT_%C2%ADNOT_%C2%ADYET_%C2%ADVALID.

If you look closely, they contain `%C2%AD` which is "SOFT HYPHEN" Unicode character.

**Comment by mukrop** [comment]
True, thanks for letting us know! I'll try to issue a fix in the following days.
(This was accidentally created when fixing a problem with headline wrapping.)
