### ISSUE TITLE
Analyse Internet-wide scan dataset

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#4]
Ask Petr Sekan or Matus Nemec to help.

**Comment by mukrop** [comment]
Initial email sent.

**Comment by mukrop** [comment]
After a short discussion, it seems Censys is not a good option. Instead, let's use Rapid7's Sonar data: https://opendata.rapid7.com/sonar.ssl/. Petr Sekan has experience with using it.

**Comment by zacikpa** [comment]
I had a quick look at the Rapid7 dataset and it looks like it only contains endpoint certificates without their CAs, as you said.

**Comment by mukrop** [comment]
Pity :-/. I'll ask Petr if he knows more about it.

**Comment by mukrop** [comment]
Update: I've uploaded to gDrive the simple python script Petr used to process the certificates individually.

**Comment by mukrop** [comment]
Long-term goal realized in https://github.com/crocs-muni/cert-validation-stats
Closing here.
