### ISSUE TITLE
Not so usable without JavaScript

### ISSUE THREAD

**Issue by mgrabovsky** [crocs-muni/usable-cert-validation#41]
Currently, the "rolldowns" with details about various errors cannot be expanded without JavaScript enabled, which makes the page somewhat less usable.

One solution would be to use the [`<details>` and `<summary>`](https://html.spec.whatwg.org/multipage/interactive-elements.html) HTML5 elements, although they are not [universally supported](https://caniuse.com/#feat=details).

Another solution, in the spirit of [progressive enhancement](https://www.w3.org/wiki/Graceful_degradation_versus_progressive_enhancement) and unobtrusive JavaScript, the rolldowns could be expanded by default and only collapsed upon page load in browsers that run scripts.

**Comment by mukrop** [comment]
True. The second solution is preferred. Feel free to do it you have time and the right mood. If not, I'll get to it eventually :-).
