### ISSUE TITLE
Display the reasoning of the deprecation status publicly

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#79]
Some errors are denoted as deprecated with the textual reasoning saved in the `deprecated` attribute. This string should be displayed in the error box (probably below the documentation with the cross icon). Some reasonings may need to be reformulated so that they are not identical to the documentation (instead, say that the current documentation states the error is not used).

**Comment by mukrop** [comment]
May be interesting for @valcikeric.

**Comment by valcikeric** [comment]
Yes, I will take a look at this.

**Comment by valcikeric** [comment]
Resolved by #80.
