### ISSUE TITLE
Choose and set up relevant thesis topics in IS

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#8]

**Comment by mukrop** [comment]
@zacikpa: Can you please read the thesis topic description I wrote to see if it looks interesting enough for a Bc student and if I had not forgotten something you would find important?
https://is.muni.cz/auth/rozpis/tema?fakulta=1433;obdobi=6724;sorter=vedouci;balik=1275;tema=355910;uplne_info=1

**Comment by zacikpa** [comment]
Everything looks fine to me!
