### ISSUE TITLE
Make a poster for student positions/theses

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#9]

**Comment by mukrop** [comment]
Done. Hanging in front of the lab.

**Comment by petrs** [comment]
Would you mind to upload posters and other artifacts to repo?

**Comment by mukrop** [comment]
Hm, it's in our work gDrive. I'm not sure it makes sense to have it in the repository.
(But I can give you the source or access to the gDrive folder if you want.)
