### ISSUE TITLE
Refactor YML-to-CERT generator use

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/usable-cert-validation#91]
In this issue I summarize suboptimal points of #86 to be refactored in the upcoming months.
* [x] Travis installs go manually (download, untar, export paths). Is this necessary? Is the local Go installation insufficient? Are no relevant apt addons available for this?
* [x] The modified go crypto library is currently hosted at Pavel's personal profile. Either let's incorporate it directly into this repository (preferred if it's small enough) or move it under the lab's profile.
* [x] Related: Is the whole library necessary? What about just cutting a part we need and keeping that as parallel functions next to the default implementation? The current setting breaks local go settings for all users wanting to build it locally (it changes crucial variables such as GOPATH and exports them system-wide!).
* [x] Another related: Please make the adjusted library in a way that it can reasonably live with the original version. Your current Travis setup replaces the orignal version!

**Comment by zacikpa** [comment]
> Travis installs go manually (download, untar, export paths). Is this necessary? Is the local Go installation insufficient? Are no relevant apt addons available for this?

Solved. We now use [gimme](https://github.com/travis-ci/gimme) to install Go in Travis.

> The modified go crypto library is currently hosted at Pavel's personal profile. Either let's incorporate it directly into this repository (preferred if it's small enough) or move it under the lab's profile.

I moved the modified part of it into our repo at _utils/yml2cert/cryptobyte_. I left eg. tests there as well, but I can delete them.

> Related: Is the whole library necessary? What about just cutting a part we need and keeping that as parallel functions next to the default implementation? The current setting breaks local go settings for all users wanting to build it locally (it changes crucial variables such as GOPATH and exports them system-wide!).
Another related: Please make the adjusted library in a way that it can reasonably live with the original version. Your current Travis setup replaces the orignal version!

Both problems are solved now. The modified part of crypto in our repo is now a standalone Go module (though Go's support of importing such modules is a bit complicated). GOPATH and GOROOT are not used at all.

I will not close this issue yet, let me know whether you find the solutions adequate, please. Thanks for pointing out the issues, helped me a lot!

**Comment by mukrop** [comment]
OK, thanks. I've done just a couple small polishing steps (adding compiled files to gitignore, documenting the unintuitive command using Gimme, ...).
